# index_tiles.py ID  -> writes oldmaps/ID/tiles.js listing which tiles exist (run from the repo root)
import os, json, sys
mid = sys.argv[1]; root = f"oldmaps/{mid}"; idx = {}
for z in os.listdir(root):
    if not z.isdigit(): continue
    for x in os.listdir(f"{root}/{z}"):
        idx.setdefault(int(z), {})[int(x)] = sorted(int(f[:-5]) for f in os.listdir(f"{root}/{z}/{x}") if f.endswith(".webp"))
idx = {z: dict(sorted(v.items())) for z, v in sorted(idx.items())}
open(f"{root}/tiles.js", "w").write(
    "/* GENERATED by tools/oldmaps/index_tiles.py — do not edit by hand.\n"
    "   Which tiles exist for this map: {zoom: {x: [y, ...]}}. */\n"
    "var OLD_MAP_TILES=window.OLD_MAP_TILES||{};\n"
    f"OLD_MAP_TILES[\"{mid}\"]=" + json.dumps(idx, separators=(",", ":")) + ";\n")
print(sum(len(ys) for v in idx.values() for ys in v.values()), "tiles indexed")
